company_name: 
  Red Bull

project_description: 
  Red Bull seeks to strengthen its presence among young adults by focusing on promoting its involvement in extreme sports and creative arts. 
  The project aims to engage the 18–26 age group through digital storytelling and immersive events, showcasing the dynamic lifestyle that Red Bull 
  represents. This includes highlighting Red Bull's sponsorship of emerging talent in skateboarding, street art, and music, along with offering 
  exclusive content to build deeper connections with its audience.
